'use strict';

const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { spawnSync } = require('node:child_process');

const repoRoot = path.resolve(__dirname, '..');
const cliJs = path.join(repoRoot, 'bin', 'atris.js');
const cliShim = path.join(repoRoot, 'bin', 'atris');

function run(args, cwd, env = {}) {
  return spawnSync(process.execPath, [cliJs, ...args], {
    cwd,
    encoding: 'utf8',
    env: { ...process.env, ATRIS_SKIP_UPDATE_CHECK: '1', ...env },
    timeout: 30000,
  });
}

function makeTempWorkspace() {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'atris-dogfood-p1-'));
  spawnSync('git', ['init', '-b', 'main', '-q'], { cwd: dir });
  fs.mkdirSync(path.join(dir, 'atris'), { recursive: true });
  fs.writeFileSync(path.join(dir, 'atris', 'atris.md'), '# atris\n');
  fs.writeFileSync(path.join(dir, 'atris', 'MAP.md'), '# MAP\n\nplaceholder content generated by your AI agent\n');
  fs.mkdirSync(path.join(dir, '.atris', 'state'), { recursive: true });
  return dir;
}

test('public bin shim is tiny and points at atris.js', () => {
  assert.ok(fs.existsSync(cliShim));
  const stat = fs.statSync(cliShim);
  assert.ok(stat.size < 1024, `shim too large: ${stat.size}`);
  const body = fs.readFileSync(cliShim, 'utf8');
  assert.match(body, /^#!/);
  assert.match(body, /atris\.js/);
  assert.match(body, /\bexec node\b/);
});

test('doctor --json reports node and task-support', () => {
  const dir = makeTempWorkspace();
  try {
    const result = run(['doctor', '--json'], dir);
    assert.equal(result.status, 0, result.stderr || result.stdout);
    const payload = JSON.parse(result.stdout);
    assert.equal(payload.ok, true);
    assert.equal(payload.action, 'doctor');
    assert.ok(payload.node && payload.node.version);
    assert.equal(typeof payload.task_support, 'boolean');
    assert.ok(payload.workspace_root);
    assert.equal(typeof payload.cli_runnable, 'boolean');
    assert.ok(payload.bin && payload.bin.shim === true);
  } finally {
    fs.rmSync(dir, { recursive: true, force: true });
  }
});

test('radar/fleet/engine/integrations/accounts default to workspace scope', () => {
  const dir = makeTempWorkspace();
  const db = path.join(dir, 'tasks.db');
  const env = { ATRIS_TASKS_DB: db };
  try {
    const radar = run(['radar', '--json'], dir, env);
    assert.equal(radar.status, 0, radar.stderr || radar.stdout);
    const radarPayload = JSON.parse(radar.stdout);
    assert.equal(radarPayload.scope, 'workspace');
    for (const wt of radarPayload.worktrees || []) {
      assert.ok(String(wt.path).startsWith(dir), `other-repo worktree leaked: ${wt.path}`);
    }

    const fleet = run(['fleet', '--json'], dir, env);
    assert.equal(fleet.status, 0, fleet.stderr || fleet.stdout);
    const fleetPayload = JSON.parse(fleet.stdout);
    assert.equal(fleetPayload.scope, 'workspace');
    assert.equal(fleetPayload.hub, null);

    const engine = run(['engine', 'list', '--json'], dir, env);
    assert.equal(engine.status, 0, engine.stderr || engine.stdout);
    const enginePayload = JSON.parse(engine.stdout);
    assert.equal(enginePayload.scope, 'workspace');
    assert.ok(Array.isArray(enginePayload.engines));
    assert.ok(enginePayload.engines.every((e) => e.installed || e.default || e.health?.status === 'ready'));

    const integrations = run(['integrations', '--json'], dir, env);
    assert.equal(integrations.status, 0, integrations.stderr || integrations.stdout);
    const integrationsPayload = JSON.parse(integrations.stdout);
    assert.equal(integrationsPayload.scope, 'workspace');

    const accounts = run(['accounts', '--json'], dir, env);
    assert.equal(accounts.status, 0, accounts.stderr || accounts.stdout);
    const accountsPayload = JSON.parse(accounts.stdout);
    assert.equal(accountsPayload.scope, 'workspace');
  } finally {
    fs.rmSync(dir, { recursive: true, force: true });
  }
});

test('verify exits 1 when MAP issues exist', () => {
  const dir = makeTempWorkspace();
  try {
    const result = run(['verify'], dir);
    assert.equal(result.status, 1, result.stdout);
    assert.match(result.stdout, /issue/i);
  } finally {
    fs.rmSync(dir, { recursive: true, force: true });
  }
});

test('land in empty repo prints one-line error without stack', () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'atris-land-empty-'));
  try {
    spawnSync('git', ['init', '-b', 'main', '-q'], { cwd: dir });
    const result = run(['land'], dir);
    assert.equal(result.status, 1);
    const err = `${result.stderr || ''}${result.stdout || ''}`;
    assert.match(err, /no commits yet/i);
    assert.doesNotMatch(err, /at Object\.landCommand|Error: no master/);
    assert.doesNotMatch(err, /node:internal/);
  } finally {
    fs.rmSync(dir, { recursive: true, force: true });
  }
});

test('recap does not claim tests passed for a file-exists verifier', () => {
  const { buildRecapData, renderShare, renderRecap } = require('../commands/recap');
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'atris-recap-file-'));
  try {
    process.env.ATRIS_TASKS_DB = path.join(dir, 'tasks.db');
    const taskDb = require('../lib/task-db');
    taskDb.close();
    const db = taskDb.open(path.join(dir, 'tasks.db'));
    const ws = taskDb.workspaceRoot(dir);
    const { id } = taskDb.addTask(db, { title: 'Ship a note', workspaceRoot: ws, status: 'open' });
    taskDb.readyTask(db, {
      id,
      actor: 'tester',
      proof: '[verified] `test -f note.md` passed (exit 0)\nReceipt: /tmp/x.json',
    });
    db.prepare('UPDATE tasks SET status = ?, done_at = ?, updated_at = ? WHERE id = ?')
      .run('done', Date.now(), Date.now(), id);
    const data = buildRecapData(dir, { days: 7 });
    const share = renderShare(data);
    const recap = renderRecap(data);
    assert.doesNotMatch(share, /tests passed/i);
    assert.doesNotMatch(recap, /tests passed/i);
    assert.match(`${share}\n${recap}`, /test -f note\.md|file check/i);
  } finally {
    delete process.env.ATRIS_TASKS_DB;
    require('../lib/task-db').close();
    fs.rmSync(dir, { recursive: true, force: true });
  }
});
