#!/usr/bin/env python3
"""Generate tables.tex for the Seymour note from the seymour-r4 artifacts.

Reads, per SAT instance: the DIMACS header (vars, clauses), the CaDiCaL
verdict (.res), wall time (.time), DRAT proof size (.drat), and this
session's drat-trim receipt (receipts/SUMMARY.txt). Emits LaTeX rows.
Everything is read from disk; nothing is typed in by hand.
"""
import os, re, glob

R4 = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "seymour-r4")
RC = os.path.join(os.path.dirname(os.path.abspath(__file__)), "receipts", "SUMMARY.txt")

receipts = {}
with open(RC) as f:
    for line in f:
        parts = line.split()
        if len(parts) >= 2:
            receipts[parts[0]] = parts[1]

def header(base):
    with open(os.path.join(R4, base + ".cnf")) as f:
        for line in f:
            if line.startswith("p cnf"):
                _, _, v, c = line.split()
                return int(v), int(c)
    return None, None

def walltime(base):
    p = os.path.join(R4, base + ".time")
    if not os.path.exists(p):
        return None
    m = re.search(r"([\d.]+)\s+real", open(p).read())
    return float(m.group(1)) if m else None

def verdict(base):
    p = os.path.join(R4, base + ".res")
    if not os.path.exists(p):
        return "(none saved)"
    t = open(p).read()
    if "s UNSATISFIABLE" in t:
        return "UNSAT"
    if "s SATISFIABLE" in t:
        return "SAT"
    return "running"

def dratsize(base):
    p = os.path.join(R4, base + ".drat")
    return os.path.getsize(p) if os.path.exists(p) else None

def fmt_bytes(b):
    if b is None: return "--"
    if b < 1024: return f"{b}\\,B"
    if b < 1024**2: return f"{b/1024:.0f}\\,KB"
    if b < 1024**3: return f"{b/1024**2:.1f}\\,MB"
    return f"{b/1024**3:.2f}\\,GB"

def fmt_t(t):
    if t is None: return "--"
    if t < 0.1: return "$<$0.1"
    return f"{t:.0f}" if t >= 10 else f"{t:.1f}"

def row(base, desc):
    v, c = header(base)
    ver = verdict(base)
    rc = receipts.get(base, "pending")
    if ver == "running":
        rc = "--"
    t = fmt_t(walltime(base)) if ver in ("UNSAT", "SAT") else "--"
    ds = fmt_bytes(dratsize(base)) if ver == "UNSAT" or verdict(base) == "(none saved)" else "--"
    if base in ("n6", "n7", "n8", "n9"):
        ver = "UNSAT"  # no .res saved; verdict established by the verified DRAT refutation
        ds = fmt_bytes(dratsize(base))
        t = fmt_t(walltime(base))
    rcx = {"VERIFIED": "\\textsc{verified}", "FAILED": "\\textbf{FAILED}",
           "pending": "pending", "--": "--"}.get(rc, rc)
    name = base.replace("_", "\\_")
    return f"\\texttt{{{name}}} & {desc} & {v} & {c} & {t} & {ds} & {ver} & {rcx} \\\\"

lines = []
lines.append("% auto-generated by gen_tables.py; do not edit by hand")
lines.append("{\\footnotesize")
lines.append("\\setlength{\\tabcolsep}{4pt}")
lines.append("\\begin{longtable}{l l r r r r l l}")
lines.append("\\caption{All SAT instances. Columns: DIMACS size, CaDiCaL wall"
             " time (seconds), DRAT proof size, solver verdict, and the"
             " drat-trim receipt regenerated in the write-up session"
             " (2026-07-23).}\\label{tab:instances}\\\\")
lines.append("\\toprule")
lines.append("instance & meaning & vars & clauses & time & proof & verdict & drat-trim \\\\")
lines.append("\\midrule\\endfirsthead")
lines.append("\\toprule instance & meaning & vars & clauses & time & proof & verdict & drat-trim \\\\ \\midrule\\endhead")
lines.append("\\bottomrule\\endfoot")

for n in (6, 7, 8, 9):
    lines.append(row(f"n{n}", f"$n{{=}}{n}$ whole space, $\\delta^+{{\\ge}}1$, no SB"))
lines.append(row("n10_d1_sb", "$n{=}10$ whole space, $\\delta^+{\\ge}1$, full lex"))
lines.append(row("n10_d3_sb", "$n{=}10$, $\\delta^+{\\ge}3$ (lemma), full lex"))
lines.append(row("n11_d3_sb", "$n{=}11$, $\\delta^+{\\ge}3$ (lemma), full lex"))
for n in range(10, 19):
    smax = (n - 1) // 2
    for s in range(1, smax + 1):
        base = f"n{n}_s{s}"
        if not os.path.exists(os.path.join(R4, base + ".cnf")):
            continue
        lines.append(row(base, f"$n{{=}}{n}$, shard $d_0{{=}}{s}$"))
lines.append("\\end{longtable}")
lines.append("}")

with open(os.path.join(os.path.dirname(os.path.abspath(__file__)), "tables.tex"), "w") as f:
    f.write("\n".join(lines) + "\n")
print("wrote tables.tex,", len(lines), "lines")
