/* Branch-and-bound exact DFS over orbit sign assignments for CW(n,k).
 *
 * Input (stdin, generated by gendfs.py):
 *   n k m T
 *   sizes[m]
 *   T lines: t  then m pairs (re, im) of orbit character sums at frequency t
 *   m lines: orbit i: cnt then the positions
 *
 * Search c in {-1,0,1}^m, sum |c_i| * size_i == k, |sum c_i * size_i| == sqrt(k),
 * prune with | |Fpartial(t)| - sqrt(k) | <= sum_remaining |z_i(t)| at each of T
 * frequencies. At leaves, exact integer PAF check over Z; solutions printed as
 * certificate lines "n k" + entries (verified externally in Python).
 *
 * cc -O2 -o dfs dfs.c -lm
 */
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#include <time.h>

#define MAXM 72
#define MAXT 16
#define MAXN 256

static int n, k, m, T, sroot;
static int sizes[MAXM];
static double zre[MAXT][MAXM], zim[MAXT][MAXM];
static double zabs[MAXT][MAXM];
static double sufabs[MAXT][MAXM + 1]; /* sum of |z| from index i..m-1 */
static int sufw[MAXM + 1];            /* max achievable extra weight from i.. */
static int opos[MAXM][MAXN];
static int ocnt[MAXM];
static int cval[MAXM];
static long long nodes = 0, leaves = 0, found = 0;
static double t_deadline = 0;
static FILE *out;

static void emit(void)
{
    int a[MAXN];
    memset(a, 0, sizeof(a));
    for (int i = 0; i < m; i++)
        if (cval[i])
            for (int j = 0; j < ocnt[i]; j++)
                a[opos[i][j]] = cval[i];
    /* exact integer PAF */
    for (int s = 1; s < n; s++) {
        long long p = 0;
        for (int i = 0; i < n; i++)
            p += (long long)a[i] * a[(i + s) % n];
        if (p != 0)
            return;
    }
    int nz = 0;
    for (int i = 0; i < n; i++)
        if (a[i]) nz++;
    if (nz != k)
        return;
    found++;
    fprintf(out, "%d %d\n", n, k);
    for (int i = 0; i < n; i++)
        fprintf(out, "%d ", a[i]);
    fprintf(out, "\n");
    fflush(out);
    fprintf(stderr, "*** SOLUTION FOUND ***\n");
}

static void dfs(int idx, int w, int rs, double fre[], double fim[])
{
    if (++nodes % 200000000LL == 0) {
        fprintf(stderr, "  nodes=%lldM idx=%d w=%d\n", nodes / 1000000, idx, w);
        if (t_deadline > 0 && (double)clock() / CLOCKS_PER_SEC > t_deadline) {
            fprintf(stderr, "TIME CAP HIT (incomplete)\n");
            fprintf(out, "# INCOMPLETE\n");
            exit(3);
        }
    }
    if (w == k) {
        if (abs(rs) != sroot)
            return;
        /* remaining orbits all zero; final check on T freqs then exact */
        for (int t = 0; t < T; t++) {
            double mag = sqrt(fre[t] * fre[t] + fim[t] * fim[t]);
            if (fabs(mag - sroot) > 1e-6)
                return;
        }
        leaves++;
        emit();
        return;
    }
    if (idx >= m || w + sufw[idx] < k)
        return;
    /* rowsum bound: max remaining |rowsum delta| = sufw[idx] (sizes positive) */
    if (abs(rs) > sroot + sufw[idx])
        return;
    /* character bounds */
    for (int t = 0; t < T; t++) {
        double mag = sqrt(fre[t] * fre[t] + fim[t] * fim[t]);
        double R = sufabs[t][idx];
        if (mag - R > sroot + 1e-9 || mag + R < sroot - 1e-9)
            return;
    }
    /* branch: 0 first (cheap), then +1, -1 */
    cval[idx] = 0;
    dfs(idx + 1, w, rs, fre, fim);
    if (w + sizes[idx] <= k) {
        double nfre[MAXT], nfim[MAXT];
        for (int sgn = 1; sgn >= -1; sgn -= 2) {
            for (int t = 0; t < T; t++) {
                nfre[t] = fre[t] + sgn * zre[t][idx];
                nfim[t] = fim[t] + sgn * zim[t][idx];
            }
            cval[idx] = sgn;
            dfs(idx + 1, w + sizes[idx], rs + sgn * sizes[idx], nfre, nfim);
        }
        cval[idx] = 0;
    }
}

int main(int argc, char **argv)
{
    double cap = argc > 1 ? atof(argv[1]) : 0;
    if (cap > 0)
        t_deadline = cap;
    if (scanf("%d %d %d %d", &n, &k, &m, &T) != 4)
        return 2;
    sroot = (int)llround(sqrt((double)k));
    for (int i = 0; i < m; i++)
        scanf("%d", &sizes[i]);
    for (int t = 0; t < T; t++) {
        int tt;
        scanf("%d", &tt);
        for (int i = 0; i < m; i++) {
            scanf("%lf %lf", &zre[t][i], &zim[t][i]);
            zabs[t][i] = sqrt(zre[t][i] * zre[t][i] + zim[t][i] * zim[t][i]);
        }
    }
    for (int i = 0; i < m; i++) {
        scanf("%d", &ocnt[i]);
        for (int j = 0; j < ocnt[i]; j++)
            scanf("%d", &opos[i][j]);
    }
    for (int t = 0; t < T; t++) {
        sufabs[t][m] = 0;
        for (int i = m - 1; i >= 0; i--)
            sufabs[t][i] = sufabs[t][i + 1] + zabs[t][i];
    }
    sufw[m] = 0;
    for (int i = m - 1; i >= 0; i--)
        sufw[i] = sufw[i + 1] + sizes[i];
    out = fopen("dfs_out.txt", "a");
    double fre[MAXT] = {0}, fim[MAXT] = {0};
    dfs(0, 0, 0, fre, fim);
    fprintf(stderr, "DONE nodes=%lld leaves=%lld found=%lld\n", nodes, leaves, found);
    fprintf(out, "# COMPLETE n=%d k=%d found=%lld\n", n, k, found);
    fclose(out);
    return 0;
}
