#!/usr/bin/env python3
"""Search for circulant weighing matrices CW(n,k) for open Strassler cases.

Modes:
  orbit  <n> <k>        multiplier/orbit ansatz: support = union of orbits of a
                        cyclic subgroup <q> of Z_n^*, signed per orbit.
  anneal <n> <k>        simulated annealing on energy = sum_{s>0} PAF(s)^2
  k25sweep [nmax]       orbit ansatz with q=5 over all n<=nmax coprime-ish, k=25
Certificates are written to found_<n>_<k>_*.txt in cwd.
"""
import sys, math, time, random
import numpy as np
from math import gcd
from itertools import combinations

OPEN_CASES = [(105,36),(112,36),(117,36),(140,36),(180,36),(195,36),
              (116,49),(120,49),(192,49),
              (140,64),(180,64),(196,64),
              (156,81),(195,81),(198,81),
              (112,100),(120,100),(155,100),(156,100),(165,100),(182,100),(195,100)]


def exact_paf_ok(a):
    n = len(a)
    ai = [int(x) for x in a]
    for s in range(1, n):
        if sum(ai[i]*ai[(i+s) % n] for i in range(n)) != 0:
            return False
    return True


def save_cert(a, n, k, tag):
    fn = f"found_{n}_{k}_{tag}.txt"
    with open(fn, "w") as f:
        f.write(f"{n} {k}\n")
        f.write(" ".join(str(int(x)) for x in a) + "\n")
    print(f"*** WROTE CERTIFICATE {fn} ***", flush=True)
    return fn


def orbits_of(n, q):
    seen = [False]*n
    orbs = []
    for x in range(n):
        if not seen[x]:
            o = []
            y = x
            while not seen[y]:
                seen[y] = True
                o.append(y)
                y = (y*q) % n
            orbs.append(sorted(o))
    return orbs


def cyclic_subgroup_generators(n, max_orbits):
    """Yield representative q (one per distinct cyclic subgroup of Z_n^*)
    whose orbit decomposition of Z_n has <= max_orbits orbits."""
    units = [u for u in range(2, n) if gcd(u, n) == 1]
    seen_subgroups = set()
    for q in units:
        # subgroup generated by q
        sg = set()
        y = 1
        while y not in sg:
            sg.add(y)
            y = (y*q) % n
        key = frozenset(sg)
        if key in seen_subgroups:
            continue
        seen_subgroups.add(key)
        orbs = orbits_of(n, q)
        if len(orbs) <= max_orbits:
            yield q, orbs


def orbit_search(n, k, max_orbits=26, cand_cap=30_000_000, verbose=True):
    """Exhaust signed unions of orbits of each cyclic subgroup <q>."""
    s = math.isqrt(k)
    assert s*s == k
    found = []
    t0 = time.time()
    for q, orbs in cyclic_subgroup_generators(n, max_orbits):
        sizes = [len(o) for o in orbs]
        m = len(orbs)
        # enumerate subsets with sizes summing to k (DFS with suffix-sum prune)
        order = sorted(range(m), key=lambda i: -sizes[i])
        suf = [0]*(m+1)
        for i in range(m-1, -1, -1):
            suf[i] = suf[i+1] + sizes[order[i]]
        subsets = []
        cap_hit = False

        def dfs(idx, rem, chosen):
            nonlocal cap_hit
            if cap_hit:
                return
            if rem == 0:
                subsets.append(list(chosen))
                if len(subsets) > 400000:
                    cap_hit = True
                return
            if idx >= m or suf[idx] < rem:
                return
            sz = sizes[order[idx]]
            if sz <= rem:
                chosen.append(order[idx])
                dfs(idx+1, rem-sz, chosen)
                chosen.pop()
            dfs(idx+1, rem, chosen)

        dfs(0, k, [])
        if cap_hit:
            if verbose:
                print(f"  n={n} k={k} q={q}: subset cap hit, skipping", flush=True)
            continue
        total_cands = sum(2**(len(ss)-1) for ss in subsets)
        if total_cands == 0:
            continue
        if total_cands > cand_cap:
            if verbose:
                print(f"  n={n} k={k} q={q}: {len(subsets)} subsets, {total_cands} cands > cap, skip", flush=True)
            continue
        if verbose:
            print(f"  n={n} k={k} q={q} (ord {len(orbs) and (n and 0) or 0}): {m} orbits sizes={sorted(sizes)}; "
                  f"{len(subsets)} subsets, {total_cands} sign-candidates", flush=True)
        ind = np.zeros((m, n), dtype=np.int8)
        for i, o in enumerate(orbs):
            ind[i, o] = 1
        batch = []
        BATCH = 8192

        def flush_batch():
            nonlocal batch
            if not batch:
                return
            A = np.array(batch, dtype=np.float64)
            F = np.fft.rfft(A, axis=1)
            P = np.abs(F)**2
            dev = np.max(np.abs(P - k), axis=1)
            hits = np.where(dev < 1e-6)[0]
            for h in hits:
                a = np.rint(A[h]).astype(int)
                if exact_paf_ok(a) and int(np.count_nonzero(a)) == k:
                    tag = f"orbit_q{q}_{len(found)}"
                    save_cert(a, n, k, tag)
                    found.append(a.copy())
            batch = []

        for ss in subsets:
            r = len(ss)
            # row sum must be +-s : sum of c_i * size_i = +-s ; fix first sign +
            base = ind[ss].astype(np.int32)
            szs = np.array([sizes[i] for i in ss])
            for mask in range(2**(r-1)):
                signs = np.ones(r, dtype=np.int32)
                for b in range(r-1):
                    if (mask >> b) & 1:
                        signs[b+1] = -1
                if abs(int(np.dot(signs, szs))) != s:
                    continue
                vec = np.dot(signs, base)
                batch.append(vec)
                if len(batch) >= BATCH:
                    flush_batch()
        flush_batch()
    if verbose:
        print(f"  orbit_search n={n} k={k} done in {time.time()-t0:.1f}s, found={len(found)}", flush=True)
    return found


def paf_np(a):
    F = np.fft.rfft(a)
    p = np.fft.irfft(np.abs(F)**2, len(a))
    return np.rint(p).astype(np.int64)


def anneal(n, k, iters=2_000_000, restarts=8, seed=None, verbose=True):
    """Simulated annealing minimizing E = sum_{s>=1} PAF(s)^2, weight fixed k."""
    rng = random.Random(seed)
    s = math.isqrt(k)
    best_overall = None
    best_E = None
    for r in range(restarts):
        # random start with weight k, row sum +- s
        a = np.zeros(n, dtype=np.int64)
        pos = rng.sample(range(n), k)
        npos = (k + s)//2
        for i, p in enumerate(pos):
            a[p] = 1 if i < npos else -1
        p = paf_np(a)
        E = int(np.sum(p[1:]**2))
        T = max(4.0, E / (4*n))
        cool = (0.01/T) ** (1.0/iters)
        for it in range(iters):
            mtype = rng.random()
            b = a.copy()
            if mtype < 0.45:
                # move a nonzero to a zero slot
                nz = np.flatnonzero(b)
                z = np.flatnonzero(b == 0)
                if len(z) == 0:
                    continue
                i = int(nz[rng.randrange(len(nz))]); j = int(z[rng.randrange(len(z))])
                b[j] = b[i]; b[i] = 0
            elif mtype < 0.9:
                # swap two entries with different values
                i = rng.randrange(n); j = rng.randrange(n)
                if b[i] == b[j]:
                    continue
                b[i], b[j] = b[j], b[i]
            else:
                # flip signs of one +1 and one -1 (preserves row sum)
                pp = np.flatnonzero(b == 1); nn = np.flatnonzero(b == -1)
                if len(pp) == 0 or len(nn) == 0:
                    continue
                b[int(pp[rng.randrange(len(pp))])] = -1
                b[int(nn[rng.randrange(len(nn))])] = 1
            p2 = paf_np(b)
            E2 = int(np.sum(p2[1:]**2))
            if E2 <= E or rng.random() < math.exp((E - E2)/max(T, 1e-9)):
                a, E = b, E2
                if E == 0:
                    if exact_paf_ok(a) and int(np.count_nonzero(a)) == k:
                        save_cert(a, n, k, f"anneal_r{r}")
                        return a, 0
            T *= cool
        if best_E is None or E < best_E:
            best_E, best_overall = E, a.copy()
        if verbose:
            print(f"  anneal n={n} k={k} restart {r}: final E={E} (best {best_E})", flush=True)
    return best_overall, best_E


def k25_sweep(nmax=200, nmin=25):
    """Orbit ansatz with q=5 for CW(n,25); report any hit (properness checked
    by verify.py afterwards). Only n with gcd(n,5)=1 (multiplier applies)."""
    hits = []
    for n in range(nmin, nmax+1):
        if gcd(n, 5) != 1:
            continue
        orbs = orbits_of(n, 5)
        f = orbit_search_fixed_q(n, 25, 5, orbs)
        for a in f:
            hits.append((n, a))
    return hits


def orbit_search_fixed_q(n, k, q, orbs):
    s = math.isqrt(k)
    sizes = [len(o) for o in orbs]
    m = len(orbs)
    found = []
    idxs = [i for i in range(m) if sizes[i] <= k]
    # DFS subsets summing to k
    order = sorted(idxs, key=lambda i: -sizes[i])
    M = len(order)
    suf = [0]*(M+1)
    for i in range(M-1, -1, -1):
        suf[i] = suf[i+1] + sizes[order[i]]
    subsets = []

    def dfs(idx, rem, chosen):
        if rem == 0:
            subsets.append(list(chosen)); return
        if idx >= M or suf[idx] < rem or len(subsets) > 2_000_000:
            return
        sz = sizes[order[idx]]
        if sz <= rem:
            chosen.append(order[idx]); dfs(idx+1, rem-sz, chosen); chosen.pop()
        dfs(idx+1, rem, chosen)

    dfs(0, k, [])
    ind = np.zeros((m, n), dtype=np.int32)
    for i, o in enumerate(orbs):
        ind[i, o] = 1
    for ss in subsets:
        r = len(ss)
        base = ind[ss]
        szs = np.array([sizes[i] for i in ss])
        for mask in range(2**(r-1)):
            signs = np.ones(r, dtype=np.int32)
            for b in range(r-1):
                if (mask >> b) & 1:
                    signs[b+1] = -1
            if abs(int(np.dot(signs, szs))) != s:
                continue
            vec = np.dot(signs, base)
            F = np.fft.rfft(vec)
            if np.max(np.abs(np.abs(F)**2 - k)) < 1e-6:
                a = vec.astype(int)
                if exact_paf_ok(a):
                    save_cert(a, n, k, f"k25_q5")
                    found.append(a)
    return found


if __name__ == "__main__":
    mode = sys.argv[1]
    if mode == "orbit":
        n, k = int(sys.argv[2]), int(sys.argv[3])
        orbit_search(n, k)
    elif mode == "orbit_all":
        for n, k in OPEN_CASES:
            print(f"== orbit search CW({n},{k}) ==", flush=True)
            orbit_search(n, k)
    elif mode == "anneal":
        n, k = int(sys.argv[2]), int(sys.argv[3])
        iters = int(sys.argv[4]) if len(sys.argv) > 4 else 2_000_000
        restarts = int(sys.argv[5]) if len(sys.argv) > 5 else 8
        a, E = anneal(n, k, iters=iters, restarts=restarts)
        print(f"best energy for CW({n},{k}): {E}")
        np.save(f"best_anneal_{n}_{k}.npy", a)
    elif mode == "k25sweep":
        nmax = int(sys.argv[2]) if len(sys.argv) > 2 else 200
        nmin = int(sys.argv[3]) if len(sys.argv) > 3 else 25
        hits = k25_sweep(nmax, nmin)
        print(f"k25 sweep done, hits: {[(n,) for n,_ in hits]}")
    else:
        print("unknown mode")
